"""Initial migration

Revision ID: 7700afe4154e
Revises: 
Create Date: 2025-01-09 15:36:16.149086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7700afe4154e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_spots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.Column('robot_id', sa.String(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('line_specifications', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Date(), nullable=True),
    sa.Column('estimated_completion', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'IN_PROGRESS', 'CANCELLED', 'MAINTENANCE', 'ERROR', name='robotstatus'), nullable=True),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('paint_level', sa.Float(), nullable=True),
    sa.Column('current_coordinates', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_robot_id'), 'robots', ['robot_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'IN_OPERATION', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('area_dimensions', sa.JSON(), nullable=True),
    sa.Column('quality_requirements', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index(op.f('ix_robots_robot_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_table('parking_spots')
    # ### end Alembic commands ###
